server:
  min_port: 39001
  max_port: 39005
  max_shutdown_interval: 600
instance:
  id: "yaml-instance-001"
  challenge_type: "drag-drop-v1"
balancer:
  host: "localhost"
  port: 50051
logging:
  level: "debug"