// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: captcha_v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEvent_EventType int32

const (
	ClientEvent_FRONTEND_EVENT    ClientEvent_EventType = 0
	ClientEvent_CONNECTION_CLOSED ClientEvent_EventType = 1
	ClientEvent_BALANCER_EVENT    ClientEvent_EventType = 2
)

// Enum value maps for ClientEvent_EventType.
var (
	ClientEvent_EventType_name = map[int32]string{
		0: "FRONTEND_EVENT",
		1: "CONNECTION_CLOSED",
		2: "BALANCER_EVENT",
	}
	ClientEvent_EventType_value = map[string]int32{
		"FRONTEND_EVENT":    0,
		"CONNECTION_CLOSED": 1,
		"BALANCER_EVENT":    2,
	}
)

func (x ClientEvent_EventType) Enum() *ClientEvent_EventType {
	p := new(ClientEvent_EventType)
	*p = x
	return p
}

func (x ClientEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_captcha_v1_proto_enumTypes[0].Descriptor()
}

func (ClientEvent_EventType) Type() protoreflect.EnumType {
	return &file_captcha_v1_proto_enumTypes[0]
}

func (x ClientEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientEvent_EventType.Descriptor instead.
func (ClientEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_captcha_v1_proto_rawDescGZIP(), []int{2, 0}
}

type ChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Complexity    int32                  `protobuf:"varint,1,opt,name=complexity,proto3" json:"complexity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_captcha_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_captcha_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeRequest) GetComplexity() int32 {
	if x != nil {
		return x.Complexity
	}
	return 0
}

type ChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Html          string                 `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_captcha_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_captcha_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ChallengeResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ChallengeResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

type ClientEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     ClientEvent_EventType  `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=captcha.v1.ClientEvent_EventType" json:"event_type,omitempty"`
	ChallengeId   string                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_captcha_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_captcha_v1_proto_rawDescGZIP(), []int{2}
}

func (x *ClientEvent) GetEventType() ClientEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return ClientEvent_FRONTEND_EVENT
}

func (x *ClientEvent) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ClientEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Result
	//	*ServerEvent_ClientJs
	//	*ServerEvent_ClientData
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_captcha_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_captcha_v1_proto_rawDescGZIP(), []int{3}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetResult() *ServerEvent_ChallengeResult {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ServerEvent) GetClientJs() *ServerEvent_RunClientJS {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_ClientJs); ok {
			return x.ClientJs
		}
	}
	return nil
}

func (x *ServerEvent) GetClientData() *ServerEvent_SendClientData {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_ClientData); ok {
			return x.ClientData
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Result struct {
	Result *ServerEvent_ChallengeResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type ServerEvent_ClientJs struct {
	ClientJs *ServerEvent_RunClientJS `protobuf:"bytes,2,opt,name=client_js,json=clientJs,proto3,oneof"`
}

type ServerEvent_ClientData struct {
	ClientData *ServerEvent_SendClientData `protobuf:"bytes,3,opt,name=client_data,json=clientData,proto3,oneof"`
}

func (*ServerEvent_Result) isServerEvent_Event() {}

func (*ServerEvent_ClientJs) isServerEvent_Event() {}

func (*ServerEvent_ClientData) isServerEvent_Event() {}

type ServerEvent_ChallengeResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId       string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	ConfidencePercent int32                  `protobuf:"varint,2,opt,name=confidence_percent,json=confidencePercent,proto3" json:"confidence_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerEvent_ChallengeResult) Reset() {
	*x = ServerEvent_ChallengeResult{}
	mi := &file_captcha_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_ChallengeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_ChallengeResult) ProtoMessage() {}

func (x *ServerEvent_ChallengeResult) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_ChallengeResult.ProtoReflect.Descriptor instead.
func (*ServerEvent_ChallengeResult) Descriptor() ([]byte, []int) {
	return file_captcha_v1_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ServerEvent_ChallengeResult) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ServerEvent_ChallengeResult) GetConfidencePercent() int32 {
	if x != nil {
		return x.ConfidencePercent
	}
	return 0
}

type ServerEvent_RunClientJS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	JsCode        string                 `protobuf:"bytes,2,opt,name=js_code,json=jsCode,proto3" json:"js_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_RunClientJS) Reset() {
	*x = ServerEvent_RunClientJS{}
	mi := &file_captcha_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_RunClientJS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_RunClientJS) ProtoMessage() {}

func (x *ServerEvent_RunClientJS) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_RunClientJS.ProtoReflect.Descriptor instead.
func (*ServerEvent_RunClientJS) Descriptor() ([]byte, []int) {
	return file_captcha_v1_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ServerEvent_RunClientJS) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ServerEvent_RunClientJS) GetJsCode() string {
	if x != nil {
		return x.JsCode
	}
	return ""
}

type ServerEvent_SendClientData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_SendClientData) Reset() {
	*x = ServerEvent_SendClientData{}
	mi := &file_captcha_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_SendClientData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_SendClientData) ProtoMessage() {}

func (x *ServerEvent_SendClientData) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_SendClientData.ProtoReflect.Descriptor instead.
func (*ServerEvent_SendClientData) Descriptor() ([]byte, []int) {
	return file_captcha_v1_proto_rawDescGZIP(), []int{3, 2}
}

func (x *ServerEvent_SendClientData) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ServerEvent_SendClientData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_captcha_v1_proto protoreflect.FileDescriptor

const file_captcha_v1_proto_rawDesc = "" +
	"\n" +
	"\x10captcha_v1.proto\x12\n" +
	"captcha.v1\"2\n" +
	"\x10ChallengeRequest\x12\x1e\n" +
	"\n" +
	"complexity\x18\x01 \x01(\x05R\n" +
	"complexity\"J\n" +
	"\x11ChallengeResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x12\n" +
	"\x04html\x18\x02 \x01(\tR\x04html\"\xd2\x01\n" +
	"\vClientEvent\x12@\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2!.captcha.v1.ClientEvent.EventTypeR\teventType\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\tR\vchallengeId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"J\n" +
	"\tEventType\x12\x12\n" +
	"\x0eFRONTEND_EVENT\x10\x00\x12\x15\n" +
	"\x11CONNECTION_CLOSED\x10\x01\x12\x12\n" +
	"\x0eBALANCER_EVENT\x10\x02\"\xe1\x03\n" +
	"\vServerEvent\x12A\n" +
	"\x06result\x18\x01 \x01(\v2'.captcha.v1.ServerEvent.ChallengeResultH\x00R\x06result\x12B\n" +
	"\tclient_js\x18\x02 \x01(\v2#.captcha.v1.ServerEvent.RunClientJSH\x00R\bclientJs\x12I\n" +
	"\vclient_data\x18\x03 \x01(\v2&.captcha.v1.ServerEvent.SendClientDataH\x00R\n" +
	"clientData\x1ac\n" +
	"\x0fChallengeResult\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12-\n" +
	"\x12confidence_percent\x18\x02 \x01(\x05R\x11confidencePercent\x1aI\n" +
	"\vRunClientJS\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x17\n" +
	"\ajs_code\x18\x02 \x01(\tR\x06jsCode\x1aG\n" +
	"\x0eSendClientData\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04dataB\a\n" +
	"\x05event2\xaa\x01\n" +
	"\x0eCaptchaService\x12M\n" +
	"\fNewChallenge\x12\x1c.captcha.v1.ChallengeRequest\x1a\x1d.captcha.v1.ChallengeResponse\"\x00\x12I\n" +
	"\x0fMakeEventStream\x12\x17.captcha.v1.ClientEvent\x1a\x17.captcha.v1.ServerEvent\"\x00(\x010\x01B\x11Z\x0f./pb/captcha/v1b\x06proto3"

var (
	file_captcha_v1_proto_rawDescOnce sync.Once
	file_captcha_v1_proto_rawDescData []byte
)

func file_captcha_v1_proto_rawDescGZIP() []byte {
	file_captcha_v1_proto_rawDescOnce.Do(func() {
		file_captcha_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_captcha_v1_proto_rawDesc), len(file_captcha_v1_proto_rawDesc)))
	})
	return file_captcha_v1_proto_rawDescData
}

var file_captcha_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_captcha_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_captcha_v1_proto_goTypes = []any{
	(ClientEvent_EventType)(0),          // 0: captcha.v1.ClientEvent.EventType
	(*ChallengeRequest)(nil),            // 1: captcha.v1.ChallengeRequest
	(*ChallengeResponse)(nil),           // 2: captcha.v1.ChallengeResponse
	(*ClientEvent)(nil),                 // 3: captcha.v1.ClientEvent
	(*ServerEvent)(nil),                 // 4: captcha.v1.ServerEvent
	(*ServerEvent_ChallengeResult)(nil), // 5: captcha.v1.ServerEvent.ChallengeResult
	(*ServerEvent_RunClientJS)(nil),     // 6: captcha.v1.ServerEvent.RunClientJS
	(*ServerEvent_SendClientData)(nil),  // 7: captcha.v1.ServerEvent.SendClientData
}
var file_captcha_v1_proto_depIdxs = []int32{
	0, // 0: captcha.v1.ClientEvent.event_type:type_name -> captcha.v1.ClientEvent.EventType
	5, // 1: captcha.v1.ServerEvent.result:type_name -> captcha.v1.ServerEvent.ChallengeResult
	6, // 2: captcha.v1.ServerEvent.client_js:type_name -> captcha.v1.ServerEvent.RunClientJS
	7, // 3: captcha.v1.ServerEvent.client_data:type_name -> captcha.v1.ServerEvent.SendClientData
	1, // 4: captcha.v1.CaptchaService.NewChallenge:input_type -> captcha.v1.ChallengeRequest
	3, // 5: captcha.v1.CaptchaService.MakeEventStream:input_type -> captcha.v1.ClientEvent
	2, // 6: captcha.v1.CaptchaService.NewChallenge:output_type -> captcha.v1.ChallengeResponse
	4, // 7: captcha.v1.CaptchaService.MakeEventStream:output_type -> captcha.v1.ServerEvent
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_captcha_v1_proto_init() }
func file_captcha_v1_proto_init() {
	if File_captcha_v1_proto != nil {
		return
	}
	file_captcha_v1_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerEvent_Result)(nil),
		(*ServerEvent_ClientJs)(nil),
		(*ServerEvent_ClientData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_captcha_v1_proto_rawDesc), len(file_captcha_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_captcha_v1_proto_goTypes,
		DependencyIndexes: file_captcha_v1_proto_depIdxs,
		EnumInfos:         file_captcha_v1_proto_enumTypes,
		MessageInfos:      file_captcha_v1_proto_msgTypes,
	}.Build()
	File_captcha_v1_proto = out.File
	file_captcha_v1_proto_goTypes = nil
	file_captcha_v1_proto_depIdxs = nil
}
