// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: balancer_v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterInstanceRequest_EventType int32

const (
	RegisterInstanceRequest_UNKNOWN   RegisterInstanceRequest_EventType = 0
	RegisterInstanceRequest_READY     RegisterInstanceRequest_EventType = 1
	RegisterInstanceRequest_NOT_READY RegisterInstanceRequest_EventType = 2
	RegisterInstanceRequest_STOPPED   RegisterInstanceRequest_EventType = 3
)

// Enum value maps for RegisterInstanceRequest_EventType.
var (
	RegisterInstanceRequest_EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "READY",
		2: "NOT_READY",
		3: "STOPPED",
	}
	RegisterInstanceRequest_EventType_value = map[string]int32{
		"UNKNOWN":   0,
		"READY":     1,
		"NOT_READY": 2,
		"STOPPED":   3,
	}
)

func (x RegisterInstanceRequest_EventType) Enum() *RegisterInstanceRequest_EventType {
	p := new(RegisterInstanceRequest_EventType)
	*p = x
	return p
}

func (x RegisterInstanceRequest_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterInstanceRequest_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_balancer_v1_proto_enumTypes[0].Descriptor()
}

func (RegisterInstanceRequest_EventType) Type() protoreflect.EnumType {
	return &file_balancer_v1_proto_enumTypes[0]
}

func (x RegisterInstanceRequest_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterInstanceRequest_EventType.Descriptor instead.
func (RegisterInstanceRequest_EventType) EnumDescriptor() ([]byte, []int) {
	return file_balancer_v1_proto_rawDescGZIP(), []int{0, 0}
}

type RegisterInstanceResponse_Status int32

const (
	RegisterInstanceResponse_SUCCESS RegisterInstanceResponse_Status = 0
	RegisterInstanceResponse_ERROR   RegisterInstanceResponse_Status = 1
)

// Enum value maps for RegisterInstanceResponse_Status.
var (
	RegisterInstanceResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
	}
	RegisterInstanceResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   1,
	}
)

func (x RegisterInstanceResponse_Status) Enum() *RegisterInstanceResponse_Status {
	p := new(RegisterInstanceResponse_Status)
	*p = x
	return p
}

func (x RegisterInstanceResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterInstanceResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_balancer_v1_proto_enumTypes[1].Descriptor()
}

func (RegisterInstanceResponse_Status) Type() protoreflect.EnumType {
	return &file_balancer_v1_proto_enumTypes[1]
}

func (x RegisterInstanceResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterInstanceResponse_Status.Descriptor instead.
func (RegisterInstanceResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_balancer_v1_proto_rawDescGZIP(), []int{1, 0}
}

type RegisterInstanceRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	EventType     RegisterInstanceRequest_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=balancer.v1.RegisterInstanceRequest_EventType" json:"event_type,omitempty"`
	InstanceId    string                            `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ChallengeType string                            `protobuf:"bytes,3,opt,name=challenge_type,json=challengeType,proto3" json:"challenge_type,omitempty"`
	Host          string                            `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	PortNumber    int32                             `protobuf:"varint,5,opt,name=port_number,json=portNumber,proto3" json:"port_number,omitempty"`
	Timestamp     int64                             `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInstanceRequest) Reset() {
	*x = RegisterInstanceRequest{}
	mi := &file_balancer_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstanceRequest) ProtoMessage() {}

func (x *RegisterInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balancer_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstanceRequest.ProtoReflect.Descriptor instead.
func (*RegisterInstanceRequest) Descriptor() ([]byte, []int) {
	return file_balancer_v1_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterInstanceRequest) GetEventType() RegisterInstanceRequest_EventType {
	if x != nil {
		return x.EventType
	}
	return RegisterInstanceRequest_UNKNOWN
}

func (x *RegisterInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterInstanceRequest) GetChallengeType() string {
	if x != nil {
		return x.ChallengeType
	}
	return ""
}

func (x *RegisterInstanceRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterInstanceRequest) GetPortNumber() int32 {
	if x != nil {
		return x.PortNumber
	}
	return 0
}

func (x *RegisterInstanceRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RegisterInstanceResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Status        RegisterInstanceResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=balancer.v1.RegisterInstanceResponse_Status" json:"status,omitempty"`
	Message       string                          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInstanceResponse) Reset() {
	*x = RegisterInstanceResponse{}
	mi := &file_balancer_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstanceResponse) ProtoMessage() {}

func (x *RegisterInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balancer_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstanceResponse.ProtoReflect.Descriptor instead.
func (*RegisterInstanceResponse) Descriptor() ([]byte, []int) {
	return file_balancer_v1_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterInstanceResponse) GetStatus() RegisterInstanceResponse_Status {
	if x != nil {
		return x.Status
	}
	return RegisterInstanceResponse_SUCCESS
}

func (x *RegisterInstanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_balancer_v1_proto protoreflect.FileDescriptor

const file_balancer_v1_proto_rawDesc = "" +
	"\n" +
	"\x11balancer_v1.proto\x12\vbalancer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x02\n" +
	"\x17RegisterInstanceRequest\x12M\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2..balancer.v1.RegisterInstanceRequest.EventTypeR\teventType\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12%\n" +
	"\x0echallenge_type\x18\x03 \x01(\tR\rchallengeType\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x1f\n" +
	"\vport_number\x18\x05 \x01(\x05R\n" +
	"portNumber\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"?\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05READY\x10\x01\x12\r\n" +
	"\tNOT_READY\x10\x02\x12\v\n" +
	"\aSTOPPED\x10\x03\"\x9c\x01\n" +
	"\x18RegisterInstanceResponse\x12D\n" +
	"\x06status\x18\x01 \x01(\x0e2,.balancer.v1.RegisterInstanceResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\" \n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x012x\n" +
	"\x0fBalancerService\x12e\n" +
	"\x10RegisterInstance\x12$.balancer.v1.RegisterInstanceRequest\x1a%.balancer.v1.RegisterInstanceResponse\"\x00(\x010\x01B\x12Z\x10./pb/balancer/v1b\x06proto3"

var (
	file_balancer_v1_proto_rawDescOnce sync.Once
	file_balancer_v1_proto_rawDescData []byte
)

func file_balancer_v1_proto_rawDescGZIP() []byte {
	file_balancer_v1_proto_rawDescOnce.Do(func() {
		file_balancer_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balancer_v1_proto_rawDesc), len(file_balancer_v1_proto_rawDesc)))
	})
	return file_balancer_v1_proto_rawDescData
}

var file_balancer_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_balancer_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_balancer_v1_proto_goTypes = []any{
	(RegisterInstanceRequest_EventType)(0), // 0: balancer.v1.RegisterInstanceRequest.EventType
	(RegisterInstanceResponse_Status)(0),   // 1: balancer.v1.RegisterInstanceResponse.Status
	(*RegisterInstanceRequest)(nil),        // 2: balancer.v1.RegisterInstanceRequest
	(*RegisterInstanceResponse)(nil),       // 3: balancer.v1.RegisterInstanceResponse
}
var file_balancer_v1_proto_depIdxs = []int32{
	0, // 0: balancer.v1.RegisterInstanceRequest.event_type:type_name -> balancer.v1.RegisterInstanceRequest.EventType
	1, // 1: balancer.v1.RegisterInstanceResponse.status:type_name -> balancer.v1.RegisterInstanceResponse.Status
	2, // 2: balancer.v1.BalancerService.RegisterInstance:input_type -> balancer.v1.RegisterInstanceRequest
	3, // 3: balancer.v1.BalancerService.RegisterInstance:output_type -> balancer.v1.RegisterInstanceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_balancer_v1_proto_init() }
func file_balancer_v1_proto_init() {
	if File_balancer_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balancer_v1_proto_rawDesc), len(file_balancer_v1_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balancer_v1_proto_goTypes,
		DependencyIndexes: file_balancer_v1_proto_depIdxs,
		EnumInfos:         file_balancer_v1_proto_enumTypes,
		MessageInfos:      file_balancer_v1_proto_msgTypes,
	}.Build()
	File_balancer_v1_proto = out.File
	file_balancer_v1_proto_goTypes = nil
	file_balancer_v1_proto_depIdxs = nil
}
